Style : Hover Effect & Color correction
malivinayak/Alarm-Clock pull request #5
Opened 2023-10-02 15:56 UTC by Mouli-3542

resolves : #4

2023-10-02 16:38 UTC, malivinayak requested changes
LGTM!

make requested changes I will merge the PR

2023-10-02 16:38 UTC, malivinayak commented on assets/style.css
> +.wrapper button {
Add new line before `.wrapper button {`

2023-10-02 16:38 UTC, malivinayak commented on assets/style.css
>  }
Add new line at end

2023-10-02 16:38 UTC, malivinayak commented on assets/style.css
> +    background: #EEA47FFF; /* Darker orange color on hover */
update color to something calm as per your wish

2023-10-02 16:38 UTC, malivinayak commented on assets/style.css
> +    transition: background 0.4s; /* Added a transition for smoother effect */
Remove the comment `/* Added a transition for smoother effect */`

2023-10-03 13:15 UTC, Mouli-3542 commented on assets/style.css
> +    transition: background 0.4s; /* Added a transition for smoother effect */
alright !

2023-10-03 13:34 UTC, closed without merging